### ISSUE TITLE
Support for frames in %browse magic

### ISSUE THREAD

**Issue by ideabucket** [hugetim/nbstata#12]
At the moment, the `%browse` magic only operates on the current frame, which is consistent with Stata itself.[^fn1]

However, because the `%browse` magic only works on the first line of the cell, if you want to look at the contents of another frame, you have to either use the notebook console to switch frames, or create a cell containg `cwf otherframe` and then a _second_ cell containing `%browse`, which is both messy and easy to lose track of.

It would be great to be able to explicitly specify a frame as a one-liner, e.g. `%browse if somevariable == 1, frame(someframe)`.

[^fn1]:  I don't know if `frame someframe: browse` is _supposed_ to work; it doesn't throw a prefix-not-allowed error, but it ignores the frame specifier and always browses the current frame.

**Comment by hugetim** [comment]
I like this. The only thing I'm pondering is the syntax. It's rare for Stata commands to have a `frame(someframe)` option (maybe only `frlink`?). And I don't think they'd ever allow `if somevariable == 1` for a variable not present in the *current* frame. Like we could do `%browse frame someframe: if somevariable == 1` or `%frame_browse someframe: if somevariable == 1`, but I'm not sure either is an improvement. `%frame someframe: browse if somevariable == 1` or `%frame someframe: %browse if somevariable == 1`?

**Comment by hugetim** [comment]
I'm leaning toward:

> **%<ins>frbr</ins>owse** *framename*: [*varlist*] [*if*] [*in*] [**, <ins>nol</ins>abel <ins>nof</ins>ormat**]

**Comment by ideabucket** [comment]
Is the design goal to keep the magic syntax-compatible with the underlying stata command? 

Because if that is the objective, another way to solve the problem (and potentially a more modular one) would be a `%frame` magic which functions like Stata's `frame:` prefix, but for magics, so you could say `%frame framename: %browse…` or `%frame framename: %head…`

Another possiblity that occurred to me would be a `%frame` magic that was the equivalent of wrapping the cell in `frame framename { }` but also worked on magics—but that would do unexpected things if the notebook was exported to a `.do` file, so I suspect is not a good idea.

**Comment by hugetim** [comment]
Not necessarily syntax-compatible in a strict sense, but just sort of in a similar spirit. I guess the main goal I have in mind is that it be easy/natural for Stata users to learn and remember the syntax. 

Anyway, whoops, I may have jumped the gun (but I had other work that I urgently need to procrastinate on, apparently): I went ahead and pushed a version of this. We can always revise the syntax later, though. Let me know how it strikes you in practice, or if you bump into any other issues.

**Comment by ideabucket** [comment]
Thanks! I'll give it a go and report back in a few days after I've got my current data analysis project off my desk and can update the kernel without tempting Murphy's law.

**Comment by ideabucket** [comment]
Finally had a chance to test this and it seems to be working great—thanks!
