### ISSUE TITLE
`preserve` does not persist across cells when `echo = None`

### ISSUE THREAD

**Issue by ideabucket** [hugetim/nbstata#13]
In exploratory analysis I will sometimes do this:

```stata
preserve
generate somevar = somecommand
* and various other commands
```
and run the cell, the intention being to inspect the results with a `%browse` or similar.

But if I run a cell like this, and then from another cell try to `summarize somevar`, I get a variable not found error. Similarly, if I `restore`, I get "nothing to restore, r(622);".

~The only way I can make sense of this is if nbstata is using `preserve`/`restore` itself, and unwinding my `preserve` behind the scenes. If so it might be a good idea to detect `preserve` in user input and throw an error.~

**Comment by hugetim** [comment]
No, but that makes sense that `preserve` doesn't work, now that you mention it. 

Well, does it work if you first run `%set echo=False` at the top of the notebook?

If not, (A) the explanation is that, behind the scenes, [pystata](https://www.stata.com/python/pystata/stata.html#pystata.stata.run) runs each multi-line code cell as if it were a temporary do-file. So, just as running `preserve` in a do-file doesn't carry over into interactive mode (or another do-file), it may be that `preserve` doesn't carry over across cells. 

If so, (B) they've made `preserve` work across `pystata.stata.run` calls and the reason it's not working is that you were using the (nbstata default) [`echo=None` mode](https://hugetim.github.io/nbstata/user_guide.html#echo-none-potential-for-unanticipated-errors), which is [another step more complicated](https://hugetim.github.io/nbstata/noecho.html) behind the scenes.

Either way, I'd like to fix the issue, if possible. (I routinely use `preserve` myself, though I apparently hadn't tried it in a notebook yet.) But a solution is not coming immediately to mind.

**Comment by ideabucket** [comment]
Ah, that's it all right! Works fine without `echo = None`. How unfortunate.

**Comment by hugetim** [comment]
Yes, that's good news. That means I should be able to make it work with `echo=None`, too, then. I've got an idea now: it can be implemented in a different way that I [perhaps prematurely judged too complicated](https://github.com/ticoneva/pystata-kernel/pull/18#issuecomment-1275223836).

**Comment by hugetim** [comment]
For now, I [pushed a temporary fix](https://github.com/hugetim/nbstata/releases/tag/v0.6.1) that just switches any cell with `preserve` or `restore` to "echo" mode automatically.

**Comment by hugetim** [comment]
Not planning to do anything further on this. Once Stata 18.5 is supported, with its native support for no echo, it should no longer be an issue anyhow.

**Comment by friosavila** [comment]
i would also suggest using frames for the same purpose.
that way the original data is not changed
