### ISSUE TITLE
Syntax highlighting in Jupyter Notebook

### ISSUE THREAD

**Issue by gaksaray** [hugetim/nbstata#17]
This is concerning the Notebook (not Jupyter Lab, which is handled by a [separate package](https://github.com/hugetim/jupyterlab_stata_highlight2)). `nbstata` currently doesn't show any syntax highlighting within the Notebook interface:

<img width="829" alt="Screen Shot 2023-04-04 at 4 49 02 PM" src="https://user-images.githubusercontent.com/72267919/229847972-c218f2a5-7363-4d93-97f9-640f4b7d6a69.png">

Yet the same notebook downloaded as "PDF via LaTeX" option produces a pdf document with syntax highlighting that is very close to stock Stata colors:

<img width="518" alt="Screen Shot 2023-04-04 at 4 49 33 PM" src="https://user-images.githubusercontent.com/72267919/229848369-e0707cfc-2830-44ca-9c50-b37de1b4488b.png">

Is it possible to have the syntax highlights applied to the pdf output within Notebook interface?

(On a side note, is it possible to get rid of those `<IPython.core.display.HTML object>` lines?)

**Comment by hugetim** [comment]
Thanks for raising this. I don't know the answers off-hand to what can be done about these. 

Well, on the Jupyter Notebook syntax highlighting, I think `stata_kernel` provided that somehow, so we should be able to port that over.

**Comment by gaksaray** [comment]
I suspect that it's already there.

When I open a notebook (essentially any .ipynb file written in `nbstata`) in [nbviewer.org](https://nbviewer.org), it is rendered with proper syntax highlighting (at least in IPython style):
<img width="359" alt="Screen Shot 2023-04-07 at 1 59 27 PM" src="https://user-images.githubusercontent.com/72267919/230612891-2e28ca87-6c33-4a05-af21-12f389672997.png">

Seems like the language definition is already there, mapping to Notebook default colors, but somehow not showing within the Notebook interface. Of course, I'm speculating --- I don't know what's going on under the hood to know better.

**Comment by hugetim** [comment]
I'm closing this, given the release of Jupyter Notebook 7, which uses the same extensions as Jupyter Lab.
