### ISSUE TITLE
MissingIDFieldWarning warning

### ISSUE THREAD

**Issue by gaksaray** [hugetim/nbstata#19]
`nbstata` 0.6.2 on Jupyter Notebook produces the following warning message:

```
/Users/gaksaray/anaconda3/envs/nbstata/lib/python3.10/site-packages/nbformat/__init__.py:128: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)
/Users/gaksaray/anaconda3/envs/nbstata/lib/python3.10/site-packages/notebook/services/contents/manager.py:353: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate_nb(model['content'])
```

<img width="569" alt="Screen Shot 2023-04-04 at 5 04 36 PM" src="https://user-images.githubusercontent.com/72267919/229851269-07968b9d-3177-48d9-9e97-7bc214a0e43b.png">

It doesn't seem to cause any problems but it might be worth checking at some point.

### Package versions

```
IPython          : 8.10.0
ipykernel        : 6.19.2
ipywidgets       : 8.0.4
jupyter_client   : 8.1.0
jupyter_core     : 5.3.0
jupyter_server   : 1.23.4
jupyterlab       : 3.5.3
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.7.0
notebook         : 6.5.3
qtconsole        : 5.4.0
traitlets        : 5.7.1
```

**Comment by hugetim** [comment]
Does it only produce that message when you use nbstata as the kernel? Have you checked if the message shows up for basic ipython kernel notebooks?

**Comment by gaksaray** [comment]
It does show in python kernel notebooks as well:

<img width="569" alt="Screen Shot 2023-04-06 at 10 21 41 AM" src="https://user-images.githubusercontent.com/72267919/230333807-db330fcd-7b08-4c45-8e73-63a39c65fea8.png">

So I guess this is not an `nbstata` warning then.

**Comment by hugetim** [comment]
I think I've also noticed it sometimes, so that's good to know.
