### ISSUE TITLE
Contribute to user guide + Make sure stata works

### ISSUE THREAD

**Issue by raffaem** [hugetim/nbstata#22]
I'm not sure how to contribute to the user guide.

I wanted to write to make sure that the `stata` command (that is, the CLI to Stata, not to be confused with `xstata`, which is the GUI) works, otherwise `nbstata` won't work.

And that if you are on Arch Linux and you get this error when running `stata`:
```
stata: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

You need to install [ncurses5-compat-libs](https://aur.archlinux.org/packages/ncurses5-compat-libs) from the AUR to fix it.

**Comment by hugetim** [comment]
Thanks! I can add that helpful info. (Just FYI, the source for the user guide is [this notebook](https://github.com/hugetim/nbstata/blob/master/nbs/user_guide.ipynb). The webpage is built by [Quarto via nbdev](https://github.com/hugetim/nbstata/blob/master/CONTRIBUTING.md).)
