### ISSUE TITLE
invalid config options

### ISSUE THREAD

**Issue by matuskosut** [hugetim/nbstata#27]
Kernel seems fail / not start when these config options from example in docs are included in nbstata.conf:
```
graph_width = 15cm
graph_height = 11cm
```

the error printed in notebook:
```
ModuleNotFoundError: pystata path not found
A Stata 17 installation is required to use the nbstata Stata kernel. If you already have Stata 17 installed, please specify its path in your configuration file.
```

Based on the documentation I tried other units too but with same failed result:
```
graph_width = 720px
graph_height = 480px
```

Version of nbstata used:
```
nbstata                       0.6.2
```

The only option was to omit them, which is fine for now, but generally should we expect this to work?

**Comment by hugetim** [comment]
Yes, that should work. This sounds like a bug.

**Comment by hugetim** [comment]
Temporary workaround is to omit them and then add them at the top of the notebook instead:
```
%%set
graph_width = 15cm
graph_height = 11cm
```
