### ISSUE TITLE
Display config file errors in notebook 

### ISSUE THREAD

**Issue by hugetim** [hugetim/nbstata#39]
They're not being displayed for some reason, passing silently with then only the "pystata module not found" error showing in the notebook.

**Comment by BCavani** [comment]
I've been using stata_kernel for a long time and tried to migrate to nbstata. However, after installing turns out that any command in JupyterLab yields "ModuleNotFoundError: pystata path not found. A Stata 17+ installation is required to use the nbstata Stata kernel. If you already have Stata 17+ installed, please specify its path in your configuration file." P.S.: I'm using Stata/MP 18 in a Linux machine.

Any suggestion on this?

**Comment by hugetim** [comment]
Yes. The solution is probably to specify _both_ the `stata_dir` and `edition` in a configuration file, like the example shown here: https://hugetim.github.io/nbstata/user_guide.html#configuration-optional

The name and location of the config file should be as shown here: https://hugetim.github.io/nbstata/user_guide.html#kernel-setup-options

If you've already tried to do that, check the format of the config file, as well as the name and location. (Unfortunately, due to this bug, you're not getting a more informative error message to help you, but I hope to get that fixed later this week.)

**Comment by BCavani** [comment]
Thank you @hugetim. I tried what you suggested by precisely (i) uninstalling nbstata, (ii) installing it with 

python -m nbstata.install ---prefix nbstata --conf-file

(iii) opened the file and set

[nbstata]
stata_dir = /apps/stata18/stata-mp
edition = mp
(...)

(iv) and then try running it in JupyterLab. 

However, it did not work. Did I lose any step?

**Comment by BCavani** [comment]
Super -- it worked! Thanks, @hugetim.

**Comment by hugetim** [comment]
> They're not being displayed for some reason, passing silently with then only the "pystata module not found" error showing in the notebook.

It is specifically the error in `config.Config.init_stata`, if the stata_dir and edition set in the config file do not work, that is not showing something more helpful.

**Comment by hugetim** [comment]
Fixed with https://github.com/hugetim/nbstata/commit/396ba8d5e726570caa334dd9da7f4e9581d6a632 and https://github.com/hugetim/nbstata/commit/d81ad7c15fe3f5d469bfbfa8a89dda4932765979
