### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by avila** [hugetim/nbstata#43]
Small issue with the docs. The [link in the user guide](https://hugetim.github.io/nbstata/user_guide.html) is broken: (missing Stata's version in pystata18)

#### Currently: 

> graph_format: Acceptable values are ‘png’ (the default), ‘pdf’, ‘svg’ and ‘pystata’. Specify the last option if you want to use pystata’s [default setting](https://www.stata.com/python/pystata/config.html#pystata.config.set_graph_format).

#### Fixed: 

> graph_format: Acceptable values are ‘png’ (the default), ‘pdf’, ‘svg’ and ‘pystata’. Specify the last option if you want to use pystata’s [default setting](https://www.stata.com/python/pystata18/config.html#pystata.config.set_graph_format).

```
graph_format: Acceptable values are ‘png’ (the default), ‘pdf’, ‘svg’ and ‘pystata’. Specify the 
last option if you want to use pystata’s [default setting](https://www.stata.com/python/pystata18
/config.html#pystata.config.set_graph_format).
```

**Comment by hugetim** [comment]
Ok, thanks! I'll get that fixed.
