### ISSUE TITLE
RStudio + Quarto Error

### ISSUE THREAD

**Issue by mcfibb** [hugetim/nbstata#46]
Hi there -- I absolutely love this project. I can get the Jupyter Notebook working via my terminal, and Stata is called just fine there. However, when I try to execute any Stata commands in RStudio, I'm met with the error: **/bin/sh: stata: command not found**

Any ideas? Screenshot for reference:
![Screenshot 2024-05-16 at 5 23 46 PM](https://github.com/hugetim/nbstata/assets/47189640/dfd4cc22-2611-4bf8-9c0f-113d173b4515)

And perhaps separately, a nbstata.config file wasn't automatically created, and I can't figure out how to get nbstata to recognize it on Jupyter startup (via the terminal). Any ideas for that too?

**Comment by mcfibb** [comment]
Thanks re: #1.

It was a typo in this ticket. The file is named "nbstata.conf". I installed
without specifying a configuration file, thinking that when I launched
Jupyter, it would pull from the config file on open. Does the configuration
file only work on install?

**Comment by hugetim** [comment]
No, you're right. It should pull from the config file on open. But I'm guessing it's not finding the config file you created. You can rerun the 'install' script with the '--conf-file' option to create a config file in the right place for you.
