### ISSUE TITLE
Some Magics do not function with Numpy 2.0

### ISSUE THREAD

**Issue by ibertchen** [hugetim/nbstata#48]
After upgrading Numpy to version 2.0, some Magics commands do not work correctly due to the way Numpy handles NaN. 

For example:

```
sysuse auto, clear
%head 10
```
leads to 

**browse failed.
`np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.**

The current workaround is to downgrade Numpy to version 1.26.4 or earlier.

**Comment by hugetim** [comment]
Thank you for reporting! I'll try to get a fix by the end of this month.

**Comment by hugetim** [comment]
Fixed in [v0.8.1](https://github.com/hugetim/nbstata/releases/tag/v0.8.1)
