### ISSUE TITLE
Support Quarto Parameters

### ISSUE THREAD

**Issue by hugetim** [hugetim/nbstata#51]
> I know with quarto we can set environmental variables then feed them into
python or R.
Do you think that could be done for nbstata too?

_Originally posted by @friosavila in https://github.com/hugetim/nbstata/issues/50#issuecomment-2408464054_

Definitely. I found the instructions for how to add support for that while I was researching the inline code issue:  https://quarto.org/docs/advanced/jupyter/kernel-execution.html#quarto-document-options 

Should we use globals to store the parameters? Or scalars?

I'll aim for this month.

**Comment by friosavila** [comment]
I would say globals are better, because scalars share the same namespace as
variables.

**Comment by hugetim** [comment]
Ok, the thing required to get it to work turned out to be [adding Stata support to a different package, Papermill](https://github.com/quarto-dev/quarto-cli/discussions/11094#discussioncomment-10973292): https://github.com/nteract/papermill/pull/809

I'm not sure how long it will take for the papermill maintainers to merge the PR and release a new version. Meanwhile, Parameters should work for Stata if you install my patched version of papermill like this:
pip install git+https://github.com/hugetim/papermill@patch-1

**Comment by friosavila** [comment]
thank you!
