### ISSUE TITLE
Locals, globals, dynamic text

### ISSUE THREAD

**Issue by friosavila** [hugetim/nbstata#9]
I tried to look into the documentation but couldn't find information about the following.
Is it possible to do inline coding?
for example something like this [inline](https://grodri.github.io/markstat/documentation).
So that if I type `stata e(r2)` (or similar) to display the desired outcome? (Print R2 of a regression, in line)
Thank you

**Comment by hugetim** [comment]
I think may again be more of a Quarto question. `nbstata` basically provides two well-defined interfaces:
1. A Stata [Jupyter kernel](https://docs.jupyter.org/en/latest/projects/kernels.html#kernels)
2. A Python API to assist using Stata from within Python code (currently, this is documented only in the [Developer Docs](https://hugetim.github.io/nbstata/dev_docs_index.html))

If you are using an external system (other than Jupyter Lab) like Quarto that plugs in to one of these interfaces (in Quarto's case, the kernel), your questions/doc searches are most likely better directed there.

**Comment by hugetim** [comment]
I'm really interested in learning more from your experience of using nbstata with Quarto (or other platforms), though. Anything you are willing to share would be most welcome here: https://github.com/hugetim/nbstata/discussions/10
